# Generated by Django 3.2.9 on 2021-12-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_gallery_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about/')),
                ('title', models.CharField(max_length=155)),
                ('description', models.TextField(max_length=255)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
