# Generated by Django 3.2.9 on 2021-12-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.FileField(upload_to='about/'),
        ),
    ]
