# Generated by Django 3.2.9 on 2021-12-06 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_about_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='Category',
            new_name='category',
        ),
    ]
